{"uuid": "9d6b3dab-4a29-4074-93cb-010c364734d4", "children": ["0da8dc3b-572b-40e5-bb2a-a0a8b9ad2529"], "befores": [{"name": "desktop_app", "status": "broken", "statusDetails": {"message": "playwright._impl._api_types.Error: net::ERR_CONNECTION_REFUSED at http://127.0.0.1:8000/\n=========================== logs ===========================\nnavigating to \"http://127.0.0.1:8000/\", waiting until \"load\"\n============================================================\nNote: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.\n", "trace": "  File \"C:\\Users\\shapo\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\shapo\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\shapo\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\shapo\\PycharmProjects\\local_autotests\\conftest.py\", line 115, in desktop_app\n    app.goto('/')\n  File \"C:\\Users\\shapo\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\shapo\\PycharmProjects\\local_autotests\\page_objects\\application.py\", line 32, in goto\n    self.page.goto(self.base_url + endpoint)\n  File \"C:\\Users\\shapo\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 6714, in goto\n    raise e\n  File \"C:\\Users\\shapo\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 6704, in goto\n    self._sync(\n  File \"C:\\Users\\shapo\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 90, in _sync\n    return future.result()\n  File \"C:\\Users\\shapo\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\playwright\\_impl\\_page.py\", line 470, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n  File \"C:\\Users\\shapo\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\playwright\\_impl\\_frame.py\", line 115, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\Users\\shapo\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 36, in send\n    return await self.inner_send(method, params, False)\n  File \"C:\\Users\\shapo\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 47, in inner_send\n    result = await callback.future\n"}, "steps": [{"name": "goto", "status": "broken", "statusDetails": {"message": "playwright._impl._api_types.Error: net::ERR_CONNECTION_REFUSED at http://127.0.0.1:8000/\n=========================== logs ===========================\nnavigating to \"http://127.0.0.1:8000/\", waiting until \"load\"\n============================================================\nNote: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.\n", "trace": "  File \"C:\\Users\\shapo\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\shapo\\PycharmProjects\\local_autotests\\page_objects\\application.py\", line 32, in goto\n    self.page.goto(self.base_url + endpoint)\n  File \"C:\\Users\\shapo\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 6714, in goto\n    raise e\n  File \"C:\\Users\\shapo\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 6704, in goto\n    self._sync(\n  File \"C:\\Users\\shapo\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 90, in _sync\n    return future.result()\n  File \"C:\\Users\\shapo\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\playwright\\_impl\\_page.py\", line 470, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n  File \"C:\\Users\\shapo\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\playwright\\_impl\\_frame.py\", line 115, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\Users\\shapo\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 36, in send\n    return await self.inner_send(method, params, False)\n  File \"C:\\Users\\shapo\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 47, in inner_send\n    result = await callback.future\n"}, "parameters": [{"name": "endpoint", "value": "'/'"}, {"name": "use_base_url", "value": "True"}], "start": 1649695905044, "stop": 1649695907735}], "start": 1649695904504, "stop": 1649695907746}], "start": 1649695904504, "stop": 1649695908421}